# Generated by Django 4.1.1 on 2022-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('hedescrpt', models.CharField(max_length=1000)),
                ('history', models.CharField(max_length=1000)),
                ('diagnosis', models.CharField(max_length=300)),
                ('reason', models.CharField(max_length=1000)),
            ],
        ),
    ]
